# Generated by Django 6.0.4 on 2026-04-17 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_created_at_and_more'),
        ('medical', '0002_remove_prescription_appointment_and_more'),
        ('users', '0009_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('temperature', models.FloatField(default=36.6)),
                ('systolic', models.IntegerField(default=120)),
                ('diastolic', models.IntegerField(default=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor')),
            ],
            options={
                'verbose_name_plural': 'Vitals',
                'ordering': ['-timestamp'],
            },
        ),
    ]
