# Generated by Django 5.2.7 on 2025-11-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_remove_prescription_medication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="medication",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
